#!/usr/bin/env bash

cargo fmt -- --check || {
    echo "Run: cargo fmt" >&2
    exit 1
}
cargo test -F rtlsdr || {
    echo "Tests fail" >&2
    exit 1
}

# TODO: maybe add --alltargets
cargo clippy -- -D warnings || {
    echo "Clippy fail" >&2
    exit 1
}
exit 0
