#!/bin/bash

cargo fmt -- --check || {
    echo "Run: cargo fmt" >&2
    exit 1
}
cargo test || {
    echo "Tests fail" >&2
    exit 1
}
cargo clippy -- -D warnings || {
    echo "Clippy fail" >&2
    exit 1
}
exit 0
