#!/usr/bin/env bash

cargo fmt -- --check || {
    echo "Run: cargo fmt" >&2
    exit 1
}
cargo test || {
    echo "Tests fail without rtlsdr" >&2
    exit 1
}
cargo test -F rtlsdr || {
    echo "Tests fail with rtlsdr" >&2
    exit 1
}
cargo +nightly bench --no-run -F rtlsdr || {
    echo "Benchmark builds fail" >&2
    exit 1
}

# TODO: maybe add --all-targets
cargo +nightly clippy -- -D warnings || {
    echo "Clippy fail" >&2
    exit 1
}
exit 0
