[package]
name = "rustradio-ui"
version = "0.1.21"
edition = "2024"
license = "MIT"
authors = ["Thomas Habets <thomas@habets.se>"]
readme = "README.md"
repository = "https://github.com/ThomasHabets/rustradio"
description = "Software defined radio library"
keywords = ["SDR", "radio"]

[dependencies]
async-channel = { version = "2.5.0", default-features = false }
js-sys = "0.3.102"
log = { version = "0.4.30", features = [
        "serde",
        "std", # For boxed logger.
] }
num-complex = { version = "0.4.6", features = ["serde"] }
rustradio = { version = "0.18.1", features = ["wasm"] }
rustradio_macros = "0.18.1"
serde = { version = "1.0.228", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.122"
wasm-bindgen-futures = "0.4.50"
web-sys = { version = "=0.3.102", features = [
        "DedicatedWorkerGlobalScope",
        "Document",  # Any DOM ops.
        "console", # console logging.
        "HtmlCanvasElement", # Various visualizations.
        "MessageEvent", # lower level worker startup.
        "Worker",
        "WorkerType",
        "WorkerOptions",
        "HtmlButtonElement",
        "HtmlInputElement",
        "ImageData",
        "CanvasRenderingContext2d",
        "MediaQueryList", # check if dark mode.
        "DomTokenList", # `class_list()`
] }

[dev-dependencies]
serde_json = "1.0.150"
wasm-bindgen-test = "0.3.0"

[features]
audio = [
        "web-sys/AudioBuffer",
        "web-sys/AudioBufferSourceNode",
        "web-sys/AudioContext",
        "web-sys/AudioDestinationNode",
        "web-sys/AudioParam",
        "web-sys/GainNode",
]
