#!/usr/bin/env python3
"""Regenerate our prost messages and allocation-budget schema (protoc + python protobuf).

Run from the repository root. No third-party sources are vendored. The native
RPC adapter is handwritten so it can use the budget-checking protobuf codec.
"""
import pathlib
import subprocess
import tempfile
from google.protobuf import descriptor_pb2 as pb

ROOT = pathlib.Path(__file__).resolve().parent.parent

def camel(s):
    return ''.join(w.capitalize() for w in s.lower().split('_'))

def snake(s):
    import re
    return re.sub(r'(?<!^)(?=[A-Z])', '_', s).lower()

with tempfile.TemporaryDirectory() as tmp:
    path = pathlib.Path(tmp) / 'schema.pb'
    subprocess.run(['protoc', '-I'+str(ROOT/'proto'), '--descriptor_set_out='+str(path), str(ROOT/'proto/iq_stream.proto')], check=True)
    ds = pb.FileDescriptorSet.FromString(path.read_bytes())
file = ds.file[0]
ids = {'.'+file.package+'.'+m.name: i+1 for i,m in enumerate(file.message_type)}
ids['.google.protobuf.Timestamp'] = len(ids)+1
scalar = {1:('double','f64'), 2:('float','f32'), 4:('uint64','u64'), 5:('int32','i32'), 8:('bool','bool'), 9:('string','String'), 12:('bytes="vec"','Vec<u8>'), 13:('uint32','u32'), 18:('sint64','i64')}

def kind(f):
    if f.type == f.TYPE_MESSAGE:
        name = f.type_name.split('.')[-1]
        return 'message', ('prost_types::Timestamp' if name=='Timestamp' else name)
    if f.type == f.TYPE_ENUM:
        return 'enumeration="'+f.type_name.split('.')[-1]+'"', 'i32'
    return scalar[f.type]

out = ['// @generated by tools/generate_iq_proto.py; do not edit.', '']
for m in file.message_type:
    out += ['#[derive(Clone, PartialEq, ::prost::Message)]', 'pub struct '+m.name+' {']
    for f in m.field:
        if f.HasField('oneof_index') and not f.proto3_optional:
            continue
        attr,typ = kind(f)
        if f.label == f.LABEL_REPEATED:
            attr += ', repeated'
            typ = 'Vec<'+typ+'>'
        elif f.type == f.TYPE_MESSAGE or f.proto3_optional:
            attr += ', optional'
            if m.name=='PairValue' and f.type==f.TYPE_MESSAGE:
                attr += ', boxed'
                typ = 'Box<'+typ+'>'
            typ = 'Option<'+typ+'>'
        out += ['    #[prost('+attr+', tag="'+str(f.number)+'")]', '    pub '+f.name+': '+typ+',']
    for i,one in enumerate(m.oneof_decl):
        fs = [f for f in m.field if f.HasField('oneof_index') and f.oneof_index==i and not f.proto3_optional]
        if not fs:
            continue
        out += ['    #[prost(oneof="'+snake(m.name)+'::'+camel(one.name)+'", tags="'+', '.join(str(f.number) for f in fs)+'")]', '    pub '+one.name+': Option<'+snake(m.name)+'::'+camel(one.name)+'>,']
    out += ['}', '']
    for i,one in enumerate(m.oneof_decl):
        fs = [f for f in m.field if f.HasField('oneof_index') and f.oneof_index==i and not f.proto3_optional]
        if not fs:
            continue
        out += ['pub mod '+snake(m.name)+' {', '    #[derive(Clone, PartialEq, ::prost::Oneof)]', '    pub enum '+camel(one.name)+' {']
        for f in fs:
            attr,typ = kind(f)
            if f.type == f.TYPE_MESSAGE:
                typ = 'super::'+typ
            out += ['        #[prost('+attr+', tag="'+str(f.number)+'")]', '        '+camel(f.name)+'('+typ+'),']
        out += ['    }', '}', '']
for e in file.enum_type:
    prefix = snake(e.name).upper()+'_'
    out += ['#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, ::prost::Enumeration)]', '#[repr(i32)]', 'pub enum '+e.name+' {']
    for v in e.value:
        out += ['    '+camel(v.name.removeprefix(prefix))+' = '+str(v.number)+',']
    out += ['}', '']
(ROOT/'src/iq_stream/proto.rs').write_text('\n'.join(out))
# Include Timestamp so unknown nested content is still bounded before decode.
timestamp = pb.DescriptorProto(name='Timestamp')
for number in (1,2):
    timestamp.field.add(name='value'+str(number), number=number, type=pb.FieldDescriptorProto.TYPE_INT64)
messages = list(file.message_type)+[timestamp]
# Each message gets a compact field table for inspection without decoding.
# Child ID zero means scalar/opaque bytes; positive IDs identify nested messages.
# Synthetic oneofs for proto3 optional fields are not mutually exclusive groups.
out = ['// @generated by tools/generate_iq_proto.py; do not edit.',
       '// Indexed by message ID; zero is reserved for fields without child messages.',
       '// Each field: (protobuf field number, child message ID, repeated, oneof group).',
       '// Oneof group zero means no group; positive groups share one body slot.',
       'pub(super) const SCHEMA: &[&[(u32, usize, bool, u8)]] = &[', '    &[],']
for m in messages:
    fields=[]
    for f in m.field:
        one = f.oneof_index+1 if f.HasField('oneof_index') and not f.proto3_optional else 0
        fields.append('('+str(f.number)+', '+str(ids.get(f.type_name,0))+', '+str(f.label==f.LABEL_REPEATED).lower()+', '+str(one)+')')
    out += ['    &['+', '.join(fields)+'], // '+m.name]
out += ['];']
for name in ('ClientMessage','ServerMessage','Frame','TagValue','Tag'):
    out += ['pub(super) const '+snake(name).upper()+': usize = '+str(ids['.'+file.package+'.'+name])+';']
(ROOT/'src/iq_stream/wire_schema.rs').write_text('\n'.join(out)+'\n')
subprocess.run(['rustfmt', '--edition', '2024', str(ROOT/'src/iq_stream/proto.rs'), str(ROOT/'src/iq_stream/wire_schema.rs')], check=True)
