// @generated by tools/generate_iq_proto.py; do not edit.

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientMessage {
    #[prost(oneof = "client_message::Body", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub body: Option<client_message::Body>,
}

pub mod client_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Open(super::Open),
        #[prost(message, tag = "2")]
        Frame(super::Frame),
        #[prost(message, tag = "3")]
        FlowControl(super::FlowControl),
        #[prost(message, tag = "4")]
        End(super::End),
        #[prost(message, tag = "5")]
        Complete(super::Complete),
        #[prost(message, tag = "6")]
        Cancel(super::Cancel),
        #[prost(message, tag = "7")]
        Failure(super::Failure),
    }
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerMessage {
    #[prost(oneof = "server_message::Body", tags = "1, 2, 3, 4, 5, 6")]
    pub body: Option<server_message::Body>,
}

pub mod server_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Started(super::Started),
        #[prost(message, tag = "2")]
        Frame(super::Frame),
        #[prost(message, tag = "3")]
        FlowControl(super::FlowControl),
        #[prost(message, tag = "4")]
        End(super::End),
        #[prost(message, tag = "5")]
        Complete(super::Complete),
        #[prost(message, tag = "6")]
        Failure(super::Failure),
    }
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Open {
    #[prost(uint32, tag = "1")]
    pub protocol_version: u32,
    #[prost(message, optional, tag = "2")]
    pub limits: Option<Limits>,
    #[prost(enumeration = "LossPolicy", tag = "3")]
    pub loss_policy: i32,
    #[prost(enumeration = "CompletionMode", tag = "4")]
    pub completion_mode: i32,
    #[prost(oneof = "open::Operation", tags = "5, 6")]
    pub operation: Option<open::Operation>,
}

pub mod open {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Operation {
        #[prost(message, tag = "5")]
        Upload(super::Upload),
        #[prost(message, tag = "6")]
        Download(super::Download),
    }
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Upload {
    #[prost(string, tag = "1")]
    pub destination: String,
    #[prost(message, optional, tag = "2")]
    pub description: Option<StreamDescription>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Download {
    #[prost(string, tag = "1")]
    pub source: String,
    #[prost(message, repeated, tag = "2")]
    pub accepted_encodings: Vec<Encoding>,
    #[prost(enumeration = "TagKind", repeated, tag = "3")]
    pub accepted_tag_kinds: Vec<i32>,
    #[prost(bool, tag = "4")]
    pub accept_terminal_tags: bool,
    #[prost(string, repeated, tag = "5")]
    pub accepted_opaque_codecs: Vec<String>,
    #[prost(bool, tag = "6")]
    pub accept_tag_source_ids: bool,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Started {
    #[prost(message, optional, tag = "1")]
    pub description: Option<StreamDescription>,
    #[prost(message, optional, tag = "2")]
    pub limits: Option<Limits>,
    #[prost(enumeration = "LossPolicy", tag = "3")]
    pub loss_policy: i32,
    #[prost(enumeration = "CompletionMode", tag = "4")]
    pub completion_mode: i32,
    #[prost(message, optional, tag = "5")]
    pub initial_credit: Option<FlowControl>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Limits {
    #[prost(uint32, tag = "1")]
    pub max_frame_bytes: u32,
    #[prost(uint32, tag = "2")]
    pub max_in_flight_frames: u32,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamDescription {
    #[prost(message, optional, tag = "1")]
    pub encoding: Option<Encoding>,
    #[prost(double, tag = "2")]
    pub sample_rate_hz: f64,
    #[prost(enumeration = "TagKind", repeated, tag = "3")]
    pub tag_kinds: Vec<i32>,
    #[prost(bool, tag = "4")]
    pub uses_terminal_tags: bool,
    #[prost(message, optional, tag = "5")]
    pub sample_zero_time: Option<prost_types::Timestamp>,
    #[prost(uint64, optional, tag = "6")]
    pub source_sample_offset: Option<u64>,
    #[prost(string, tag = "7")]
    pub source_id: String,
    #[prost(message, repeated, tag = "8")]
    pub properties: Vec<Property>,
    #[prost(string, repeated, tag = "9")]
    pub opaque_codecs: Vec<String>,
    #[prost(bool, tag = "10")]
    pub uses_tag_source_ids: bool,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Encoding {
    #[prost(enumeration = "ComponentType", tag = "1")]
    pub component_type: i32,
    #[prost(enumeration = "ByteOrder", tag = "2")]
    pub byte_order: i32,
    #[prost(enumeration = "SampleLayout", tag = "3")]
    pub layout: i32,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Property {
    #[prost(string, tag = "1")]
    pub key: String,
    #[prost(message, optional, tag = "2")]
    pub value: Option<TagValue>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Frame {
    #[prost(uint64, tag = "1")]
    pub sequence: u64,
    #[prost(oneof = "frame::Body", tags = "2, 3")]
    pub body: Option<frame::Body>,
}

pub mod frame {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "2")]
        Chunk(super::SampleChunk),
        #[prost(message, tag = "3")]
        Gap(super::Gap),
    }
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SampleChunk {
    #[prost(uint64, tag = "1")]
    pub first_sample: u64,
    #[prost(uint32, tag = "2")]
    pub sample_count: u32,
    #[prost(bytes = "vec", tag = "3")]
    pub samples: Vec<u8>,
    #[prost(message, repeated, tag = "4")]
    pub tags: Vec<Tag>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Gap {
    #[prost(uint64, tag = "1")]
    pub first_sample: u64,
    #[prost(uint64, tag = "2")]
    pub sample_count: u64,
    #[prost(string, tag = "3")]
    pub reason: String,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tag {
    #[prost(uint64, tag = "1")]
    pub sample_index: u64,
    #[prost(string, tag = "2")]
    pub key: String,
    #[prost(message, optional, tag = "3")]
    pub value: Option<TagValue>,
    #[prost(string, optional, tag = "4")]
    pub source_id: Option<String>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TagValue {
    #[prost(
        oneof = "tag_value::Kind",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16"
    )]
    pub kind: Option<tag_value::Kind>,
}

pub mod tag_value {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(float, tag = "1")]
        Float32Value(f32),
        #[prost(double, tag = "2")]
        Float64Value(f64),
        #[prost(bool, tag = "3")]
        BoolValue(bool),
        #[prost(sint64, tag = "4")]
        Int64Value(i64),
        #[prost(uint64, tag = "5")]
        Uint64Value(u64),
        #[prost(string, tag = "6")]
        StringValue(String),
        #[prost(bytes = "vec", tag = "7")]
        BytesValue(Vec<u8>),
        #[prost(string, tag = "8")]
        SymbolValue(String),
        #[prost(message, tag = "9")]
        ComplexValue(super::ComplexValue),
        #[prost(message, tag = "10")]
        ListValue(super::SequenceValue),
        #[prost(message, tag = "11")]
        TupleValue(super::SequenceValue),
        #[prost(message, tag = "12")]
        PairValue(super::PairValue),
        #[prost(message, tag = "13")]
        DictionaryValue(super::DictionaryValue),
        #[prost(message, tag = "14")]
        NilValue(super::NilValue),
        #[prost(string, tag = "15")]
        JsonValue(String),
        #[prost(message, tag = "16")]
        OpaqueValue(super::OpaqueValue),
    }
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ComplexValue {
    #[prost(double, tag = "1")]
    pub real: f64,
    #[prost(double, tag = "2")]
    pub imaginary: f64,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SequenceValue {
    #[prost(message, repeated, tag = "1")]
    pub values: Vec<TagValue>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PairValue {
    #[prost(message, optional, boxed, tag = "1")]
    pub first: Option<Box<TagValue>>,
    #[prost(message, optional, boxed, tag = "2")]
    pub second: Option<Box<TagValue>>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DictionaryValue {
    #[prost(message, repeated, tag = "1")]
    pub entries: Vec<DictionaryEntry>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DictionaryEntry {
    #[prost(message, optional, tag = "1")]
    pub key: Option<TagValue>,
    #[prost(message, optional, tag = "2")]
    pub value: Option<TagValue>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NilValue {}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpaqueValue {
    #[prost(string, tag = "1")]
    pub type_url: String,
    #[prost(bytes = "vec", tag = "2")]
    pub data: Vec<u8>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FlowControl {
    #[prost(uint64, tag = "1")]
    pub send_limit: u64,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct End {
    #[prost(uint64, tag = "1")]
    pub next_sequence: u64,
    #[prost(uint64, tag = "2")]
    pub next_sample: u64,
    #[prost(message, repeated, tag = "3")]
    pub tags: Vec<Tag>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Complete {
    #[prost(uint64, tag = "1")]
    pub next_sequence: u64,
    #[prost(uint64, tag = "2")]
    pub next_sample: u64,
    #[prost(enumeration = "CompletionMode", tag = "3")]
    pub completion_mode: i32,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Cancel {
    #[prost(string, tag = "1")]
    pub reason: String,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Failure {
    #[prost(uint32, tag = "1")]
    pub grpc_status_code: u32,
    #[prost(string, tag = "2")]
    pub message: String,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, ::prost::Enumeration)]
#[repr(i32)]
pub enum LossPolicy {
    Unspecified = 0,
    Lossless = 1,
    AllowGaps = 2,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, ::prost::Enumeration)]
#[repr(i32)]
pub enum CompletionMode {
    Unspecified = 0,
    Accepted = 1,
    Durable = 2,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, ::prost::Enumeration)]
#[repr(i32)]
pub enum SampleLayout {
    Unspecified = 0,
    Real = 1,
    Complex = 2,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, ::prost::Enumeration)]
#[repr(i32)]
pub enum ComponentType {
    Unspecified = 0,
    Float32 = 1,
    Float64 = 2,
    Int8 = 3,
    Uint8 = 4,
    Int16 = 5,
    Uint16 = 6,
    Int32 = 7,
    Uint32 = 8,
    Int64 = 9,
    Uint64 = 10,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, ::prost::Enumeration)]
#[repr(i32)]
pub enum ByteOrder {
    Unspecified = 0,
    LittleEndian = 1,
    BigEndian = 2,
    NotApplicable = 3,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, ::prost::Enumeration)]
#[repr(i32)]
pub enum TagKind {
    Unspecified = 0,
    Float32 = 1,
    Float64 = 2,
    Bool = 3,
    Int64 = 4,
    Uint64 = 5,
    String = 6,
    Bytes = 7,
    Symbol = 8,
    Complex = 9,
    List = 10,
    Tuple = 11,
    Pair = 12,
    Dictionary = 13,
    Nil = 14,
    Json = 15,
    Opaque = 16,
}
