// @generated by tools/generate_iq_proto.py; do not edit.
// Indexed by message ID; zero is reserved for fields without child messages.
// Each field: (protobuf field number, child message ID, repeated, oneof group).
// Oneof group zero means no group; positive groups share one body slot.
pub(super) const SCHEMA: &[&[(u32, usize, bool, u8)]] = &[
    &[],
    &[
        (1, 3, false, 1),
        (2, 11, false, 1),
        (3, 23, false, 1),
        (4, 24, false, 1),
        (5, 25, false, 1),
        (6, 26, false, 1),
        (7, 27, false, 1),
    ], // ClientMessage
    &[
        (1, 6, false, 1),
        (2, 11, false, 1),
        (3, 23, false, 1),
        (4, 24, false, 1),
        (5, 25, false, 1),
        (6, 27, false, 1),
    ], // ServerMessage
    &[
        (1, 0, false, 0),
        (2, 7, false, 0),
        (3, 0, false, 0),
        (4, 0, false, 0),
        (5, 4, false, 1),
        (6, 5, false, 1),
    ], // Open
    &[(1, 0, false, 0), (2, 8, false, 0)], // Upload
    &[
        (1, 0, false, 0),
        (2, 9, true, 0),
        (3, 0, true, 0),
        (4, 0, false, 0),
        (5, 0, true, 0),
        (6, 0, false, 0),
    ], // Download
    &[
        (1, 8, false, 0),
        (2, 7, false, 0),
        (3, 0, false, 0),
        (4, 0, false, 0),
        (5, 23, false, 0),
    ], // Started
    &[(1, 0, false, 0), (2, 0, false, 0)], // Limits
    &[
        (1, 9, false, 0),
        (2, 0, false, 0),
        (3, 0, true, 0),
        (4, 0, false, 0),
        (5, 28, false, 0),
        (6, 0, false, 0),
        (7, 0, false, 0),
        (8, 10, true, 0),
        (9, 0, true, 0),
        (10, 0, false, 0),
    ], // StreamDescription
    &[(1, 0, false, 0), (2, 0, false, 0), (3, 0, false, 0)], // Encoding
    &[(1, 0, false, 0), (2, 15, false, 0)], // Property
    &[(1, 0, false, 0), (2, 12, false, 1), (3, 13, false, 1)], // Frame
    &[
        (1, 0, false, 0),
        (2, 0, false, 0),
        (3, 0, false, 0),
        (4, 14, true, 0),
    ], // SampleChunk
    &[(1, 0, false, 0), (2, 0, false, 0), (3, 0, false, 0)], // Gap
    &[
        (1, 0, false, 0),
        (2, 0, false, 0),
        (3, 15, false, 0),
        (4, 0, false, 0),
    ], // Tag
    &[
        (1, 0, false, 1),
        (2, 0, false, 1),
        (3, 0, false, 1),
        (4, 0, false, 1),
        (5, 0, false, 1),
        (6, 0, false, 1),
        (7, 0, false, 1),
        (8, 0, false, 1),
        (9, 16, false, 1),
        (10, 17, false, 1),
        (11, 17, false, 1),
        (12, 18, false, 1),
        (13, 19, false, 1),
        (14, 21, false, 1),
        (15, 0, false, 1),
        (16, 22, false, 1),
    ], // TagValue
    &[(1, 0, false, 0), (2, 0, false, 0)], // ComplexValue
    &[(1, 15, true, 0)],                   // SequenceValue
    &[(1, 15, false, 0), (2, 15, false, 0)], // PairValue
    &[(1, 20, true, 0)],                   // DictionaryValue
    &[(1, 15, false, 0), (2, 15, false, 0)], // DictionaryEntry
    &[],                                   // NilValue
    &[(1, 0, false, 0), (2, 0, false, 0)], // OpaqueValue
    &[(1, 0, false, 0)],                   // FlowControl
    &[(1, 0, false, 0), (2, 0, false, 0), (3, 14, true, 0)], // End
    &[(1, 0, false, 0), (2, 0, false, 0), (3, 0, false, 0)], // Complete
    &[(1, 0, false, 0)],                   // Cancel
    &[(1, 0, false, 0), (2, 0, false, 0)], // Failure
    &[(1, 0, false, 0), (2, 0, false, 0)], // Timestamp
];
pub(super) const CLIENT_MESSAGE: usize = 1;
pub(super) const SERVER_MESSAGE: usize = 2;
pub(super) const FRAME: usize = 11;
pub(super) const TAG_VALUE: usize = 15;
pub(super) const TAG: usize = 14;
