name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lowdep:
    runs-on: ubuntu-latest
    name: Low dependency build
    steps:
    - uses: actions/checkout@v6
    - name: Build
      run: cargo build --verbose
    - name: Build examples
      run: cargo build --verbose --examples
  standard:
    runs-on: ubuntu-latest
    name: Standard tests
    steps:
    - uses: actions/checkout@v6
    - name: Install Rust nightly
      run: rustup install nightly
    - name: Rustup install nightly clippy
      run: rustup component add --toolchain nightly clippy
    - name: cargo install
      run: cargo install cargo-deny tickbox
    - name: apt-get update
      run:  sudo apt-get update
    - name: Install dependencies
      run:  sudo apt-get install -y librtlsdr-dev libsoapysdr-dev libjack-dev libasound-dev libfftw3-dev schedtool libpipewire-0.3-dev libvolk*-dev
    - name: Run tickbox
      run: NODIFF=true CLEANUP=true tickbox --dir tickbox/precommit --disable-tui --max-concurrency=1
  individual_features:
    runs-on: ubuntu-latest
    name: Individual features
    steps:
    - uses: actions/checkout@v6
    - name: Install Rust nightly
      run: rustup install nightly
    - name: Rustup install nightly clippy
      run: rustup component add --toolchain nightly clippy
    - name: cargo install
      run: cargo install tickbox
    - name: apt-get update
      run:  sudo apt-get update
    - name: Install dependencies
      run:  sudo apt-get install -y librtlsdr-dev libsoapysdr-dev libjack-dev libasound-dev libfftw3-dev schedtool libpipewire-0.3-dev libvolk*-dev
    - name: Run tickbox
      run: SLOW=true NODIFF=true CLEANUP=true tickbox --dir tickbox/precommit --disable-tui --max-concurrency=1 --matching '^(10|26)-.*'
#    - name: Check semver
#      uses: obi1kenobi/cargo-semver-checks-action@v2
