name: Run WASM benchmark for UI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  wasm-bench:
    runs-on: ubuntu-latest
    name: Run WASM benchmark
    steps:
    - uses: actions/checkout@v6
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2
    - name: Install wasm-pack
      run: cargo install wasm-pack --locked
    - name: Run benchmark
      run: cd rustradio-ui && wasm-pack test --release  --headless --chrome .   -- 
